/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package id.faizz.tuprak9;

import javafx.animation.PauseTransition;
import javafx.application.Application;
import javafx.stage.Stage;
import javafx.scene.Group;
import javafx.scene.Scene;
import javafx.scene.layout.Background;
import javafx.scene.layout.BackgroundImage;
import javafx.scene.layout.BackgroundPosition;
import javafx.scene.layout.BackgroundRepeat;
import javafx.scene.layout.BackgroundSize;
import javafx.scene.layout.BorderPane;
import javafx.scene.layout.HBox;
import javafx.scene.layout.Pane;
import javafx.scene.layout.Priority;
import javafx.scene.layout.Region;
import javafx.scene.layout.StackPane;
import javafx.scene.layout.VBox;
import javafx.geometry.Insets;
import javafx.geometry.Pos;
import javafx.scene.control.*;
import javafx.scene.image.Image;
import javafx.scene.image.ImageView;
import javafx.scene.paint.Color;
import javafx.scene.shape.Rectangle;
import javafx.scene.text.Font;
import javafx.scene.text.Text;
import javafx.util.Duration;

public class App extends Application {
    public void start(Stage Stage) throws Exception{
        StackPane root = new StackPane();
        Scene scene = new Scene(root, 1382, 736);

        VBox awal = new VBox();
        awal.setAlignment(Pos.CENTER);
        Image logoAwal = new Image("styles/LogoLoading.png");
        ImageView nampilin = new ImageView(logoAwal);
        awal.getChildren().add(nampilin);
    
        root.setOnMouseClicked(e -> {
            LoginPage loginPage = new LoginPage(Stage);
            loginPage.showPage();
        });

        root.getChildren().addAll(awal);
        root.getStyleClass().add("rootPane");
        scene.getStylesheets().add("styles/styles.css");
        Stage.setScene(scene);
        Stage.setTitle("Shopease");
        Stage.setMaximized(true);
        // Stage.setFullScreen(true);
        Stage.show();
    }

    public static void main(String[] args) {
        launch(args);
    }
}
