/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package id.faizz.tuprak9;
// Import statements untuk JavaFX dan kelas-kelas yang diperlukan
import javafx.animation.PauseTransition;
import javafx.application.Application;
import javafx.stage.Stage;
import javafx.scene.Group;
import javafx.scene.Scene;
import javafx.scene.layout.Background;
import javafx.scene.layout.BackgroundImage;
import javafx.scene.layout.BackgroundPosition;
import javafx.scene.layout.BackgroundRepeat;
import javafx.scene.layout.BackgroundSize;
import javafx.scene.layout.BorderPane;
import javafx.scene.layout.HBox;
import javafx.scene.layout.Pane;
import javafx.scene.layout.Priority;
import javafx.scene.layout.Region;
import javafx.scene.layout.StackPane;
import javafx.scene.layout.VBox;
import javafx.geometry.Insets;
import javafx.geometry.Pos;
import javafx.scene.control.*;
import javafx.scene.image.Image;
import javafx.scene.image.ImageView;
import javafx.scene.paint.Color;
import javafx.scene.shape.Rectangle;
import javafx.scene.text.Font;
import javafx.scene.text.Text;
import javafx.util.Duration;

// Kelas utama aplikasi yang mengimplementasikan interface Application
public class App extends Application {

    // Metode start untuk menginisialisasi dan menampilkan aplikasi
    @Override
    public void start(Stage stage) throws Exception {
        // Membuat root StackPane sebagai root dari semua node di scene
        StackPane root = new StackPane();
        Scene scene = new Scene(root, 1382, 736); // Membuat scene dengan ukuran 1382x736

        // Membuat VBox untuk tata letak awal
        VBox awal = new VBox();
        awal.setAlignment(Pos.CENTER);
        
        // Membuat ImageView untuk menampilkan logo awal
        Image logoAwal = new Image("styles/LogoLoading.png");
        ImageView nampilin = new ImageView(logoAwal);
        awal.getChildren().add(nampilin); // Menambahkan ImageView ke dalam VBox

        // Menampilkan halaman login ketika root StackPane diklik
        root.setOnMouseClicked(e -> {
            LoginPage loginPage = new LoginPage(stage);
            loginPage.showPage();
        });

        // Menambahkan VBox awal ke dalam root StackPane
        root.getChildren().addAll(awal);
        root.getStyleClass().add("rootPane"); // Menambahkan kelas CSS ke root StackPane
        scene.getStylesheets().add("styles/styles.css"); // Menambahkan stylesheet untuk styling
        stage.setScene(scene); // Menetapkan scene pada stage
        stage.setTitle("Shopease"); // Menetapkan judul jendela aplikasi
        stage.setMaximized(true); // Menetapkan jendela aplikasi menjadi maksimalkan
        // stage.setFullScreen(true); // Opsi untuk menetapkan aplikasi ke mode layar penuh
        stage.show(); // Menampilkan stage
    }

    // Metode utama untuk menjalankan aplikasi
    public static void main(String[] args) {
        launch(args);
    }
}
